BEGIN;

CREATE SCHEMA IF NOT EXISTS messenger;

CREATE TABLE IF NOT EXISTS messenger.user (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid VARCHAR NOT NULL UNIQUE,
    last_visited TIMESTAMP NOT NULL,
    identity_public_key BYTEA NOT NULL,
    signed_public_key BYTEA NOT NULL,
    master_password_hash BYTEA NOT NULL,
    protected_symmetric_key BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS messenger.user_one_time_key (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user INT NOT NULL,
    public_one_time_key BYTEA NOT NULL,
    key_number UUID NOT NULL,
    FOREIGN KEY (id_user) REFERENCES messenger.user (id)
);

CREATE TABLE IF NOT EXISTS messenger.user_data (
    id INT PRIMARY KEY,
    user_data BYTEA NOT NULL,
    FOREIGN KEY (id) REFERENCES messenger.user (id)
);

CREATE TABLE IF NOT EXISTS messenger.message_status (
    id INT PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS messenger.message (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_number UUID NOT NULL,
    id_sender INT NOT NULL,
    id_receiver INT NOT NULL,
    message BYTEA NOT NULL,
    ou_group VARCHAR,
    id_state INT NOT NULL,
    time_sent TIMESTAMP NOT NULL,
    FOREIGN KEY (id_sender) REFERENCES messenger.user (id),
    FOREIGN KEY (id_receiver) REFERENCES messenger.user (id),
    FOREIGN KEY (id_state) REFERENCES messenger.message_status(id)
);

DELETE FROM messenger.message_status;

INSERT INTO messenger.message_status (id, name) VALUES (0, 'SENT'), (1, 'RECEIVED');

COMMIT;