spring.ldap.urls=ldap://ldap:1389/
spring.ldap.base=dc=springframework,dc=org
spring.ldap.username=cn=admin,dc=springframework,dc=org
spring.ldap.password=admin
ldap.user_attribute=cn
ldap.user_filter=(uid={0})
ldap.uid=uid
ldap.password_attribute=userPassword

spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driverClassName=org.postgresql.Driver

springdoc.swagger-ui.enabled=true
spring.docker.compose.enabled=false

error.handling.exception-logging=with_stacktrace
logging.level.ROOT=DEBUG
token.signing.key=c2VjcmV0LWtleS1zZWNyZXQta2V5LXNlY3JldC1rZXktc2VjcmV0LWtleS1zZWNyZXQta2V5
