spring.ldap.urls=ldap://localhost:1389/
spring.ldap.base=dc=springframework,dc=org
spring.ldap.username=cn=admin,dc=springframework,dc=org
spring.ldap.password=admin
ldap.user_attribute=cn
ldap.user_filter=(uid={0})
ldap.uid=uid
ldap.password_attribute=userPassword
springdoc.swagger-ui.enabled=true
spring.docker.compose.enabled=true
error.handling.exception-logging=with_stacktrace
logging.level.ROOT=DEBUG
token.signing.key=c2VjcmV0LWtleS1zZWNyZXQta2V5LXNlY3JldC1rZXktc2VjcmV0LWtleS1zZWNyZXQta2V5
